<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>8f16e67f-ed85-4fc2-b2dc-ec6a57c274cc</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.8" />
    <PackageReference Include="MongoDB.Driver" Version="3.9.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PracticeProblems.Services\PracticeProblems.Services.csproj" />
    <ProjectReference Include="..\PracticeProblems.Data\PracticeProblems.Data.csproj" />
  </ItemGroup>

</Project>
